import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { UserButton } from "@/components/UserButton";
import Link from "next/link";
import { User2 } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Domain Verification Demo",
  description: "Generated by create next app, shows domain verification",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <div className="flex flex-col min-h-screen dark:bg-gray-900 ">
            <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
              <div className="container max-w-screen-lg py-3 flex items-center">
                <Link className="flex items-center justify-center" href="/">
                  <User2 />
                  <span>Domain(s) Demo</span>
                </Link>
                <nav className="ml-auto items-center flex gap-4 sm:gap-6">
                  <UserButton />
                </nav>
              </div>
            </header>
            <div className="mt-9">
              {children}
            </div>
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
